### ISSUE TITLE
Advanced Git Chapter 8 Centralized Workflow - issues with repos.zip

### ISSUE THREAD

**Issue by hazartilirot** [kodecocodes/bkk-materials#1]
Well, I've got an issue with the archive you provide in repos.zip 
https://github.com/raywenderlich/agit-materials/tree/editions/2.0/08-centralized-workflow/projects/starter

Once you unzip it some files are unstaged which prevents me from pulling and merging. I wonder what purpose of those unstaged files is.... My git version is 2.33.1

p.s.# while writing my issue I decided to change to version 1 (from 2). The issue persisted. I then executed git diff and saw there are some changes like old mode, new mode, I then googled it.... well, before all manipulation you must execute: git config.filemode false
![glitch](https://user-images.githubusercontent.com/1349977/143658446-0257f3d9-7b8c-4fcc-96f5-c9439334902d.png)

**Comment by hazartilirot** [comment]
BTW, I'm not a Mac's user. It's linux running on WSL in Windows 10. As for others you might not have the issue.

**Comment by hazartilirot** [comment]
Well, folks. The same issue you'd have in the 9-th chapter. 
Don't panic, just execute `git config core.filemode false` in each direcotory and then `rm .DS_Store` to get a clean set
![screenshot](https://user-images.githubusercontent.com/1349977/143767720-14dc497e-a579-4d61-afd6-ec75c2168265.png)
up.

**Comment by sammyd** [comment]
Hi @hazartilirot thanks for your feedback. Unfortunately you've added it to the template directory, rather than the repo for the specific book. I think, if you're looking at advanced git, the place you want to look is 

https://github.com/raywenderlich/agit

Or alternatively add it to the official errata for this edition of the book:

https://forums.raywenderlich.com/t/errata-for-advanced-git-2nd-edition/152741

Thanks again—hopefully we'll be able to address it once it gets to the right people!
